import { MenuItem } from './types';

const img = (name: string) => `/images/${name}`;

export const MEATS = [
  { id: 'asada', name: 'Asada (Beef)', tag: 'Steak' },
  { id: 'pastor', name: 'Pastor (Pork)', tag: 'Marinated Pork' },
  { id: 'pollo', name: 'Pollo (Chicken)', tag: 'Grilled Chicken' },
  { id: 'chorizo', name: 'Chorizo', tag: 'Sausage' },
  { id: 'carnitas', name: 'Carnitas', tag: 'Slow-cooked Pork' },
  { id: 'buche', name: 'Buche', tag: 'Pork Stomach' },
];

export const STYLES = [
  {
    id: 'street',
    name: 'Street Style',
    description: 'Corn tortilla, cilantro, onions, lime, and salsa',
  },
  {
    id: 'gringo',
    name: 'Flour Style',
    description: 'Flour tortilla, lettuce, tomato, cheese, and sour cream',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'street-taco',
    name: 'Street Taco',
    category: 'tacos',
    price: 2.5,
    description: 'Double corn tortillas with your choice of meat, onions, cilantro, lime, and house salsa.',
    image: img('street-tacos.jpg'),
    customizable: true,
  },
  {
    id: 'taco-harina',
    name: 'Taco de Harina',
    category: 'tacos',
    price: 3,
    description: 'Soft flour tortilla with your choice of meat, lettuce, tomato, cheese, and sour cream.',
    image: img('taco-spread.jpg'),
    customizable: true,
  },
  {
    id: 'taco-dinner',
    name: 'Taco Dinner',
    category: 'tacos',
    price: 11.5,
    description: 'Three tacos with rice, beans, grilled jalapeno, carrots, lime, and salsa on the side.',
    image: img('plate-spread.jpg'),
    customizable: true,
  },
  {
    id: 'regular-burrito',
    name: 'Regular Burrito',
    category: 'burritos',
    price: 9.5,
    description: 'Warm flour tortilla with meat, rice, beans, onions, cilantro, and salsa.',
    image: img('burrito-plate.jpg'),
    customizable: true,
  },
  {
    id: 'california-burrito',
    name: 'California Burrito',
    category: 'burritos',
    price: 11.5,
    description: 'A loaded burrito with meat, fries, cheese, sour cream, guacamole, and salsa.',
    image: img('burrito-close.jpg'),
    customizable: true,
  },
  {
    id: 'breakfast-burrito',
    name: 'Breakfast Burrito',
    category: 'burritos',
    price: 8,
    description: 'Eggs, chorizo, cheese, potatoes, and salsa wrapped in a warm flour tortilla.',
    image: img('breakfast-burrito.jpg'),
    customizable: true,
  },
  {
    id: 'quesadilla',
    name: 'Quesadilla',
    category: 'mains',
    price: 8.5,
    description: 'Toasted flour tortilla with melted cheese, your choice of meat, salsa, and sour cream.',
    image: img('quesadilla.jpg'),
    customizable: true,
  },
  {
    id: 'torta',
    name: 'Torta',
    category: 'mains',
    price: 9,
    description: 'Toasted Mexican sandwich with meat, beans, mayo, avocado, lettuce, and tomato.',
    image: img('torta-sandwich.jpg'),
    customizable: true,
  },
  {
    id: 'mulitas',
    name: 'Mulitas',
    category: 'mains',
    price: 4.5,
    description: 'Two corn tortillas with melted cheese, meat, onions, cilantro, and avocado salsa.',
    image: img('rolled-tacos.jpg'),
    customizable: true,
  },
  {
    id: 'loaded-plates',
    name: 'Loaded Plate',
    category: 'mains',
    price: 12.5,
    description: 'A full plate with rice, beans, guacamole, pico, crema, salsa, and your choice of meat.',
    image: img('loaded-plate.png'),
    customizable: true,
  },
  {
    id: 'jarritos',
    name: 'Jarritos',
    category: 'drinks',
    price: 2.75,
    description: 'Mexican glass bottle soda. Ask for the flavors available at the truck today.',
    image: img('jarritos.jpg'),
    customizable: false,
  },
  {
    id: 'coke-sprite',
    name: 'Mexican Coke / Sprite',
    category: 'drinks',
    price: 3,
    description: 'Glass bottle Mexican Coke or Sprite, served cold.',
    image: img('menu-board.jpg'),
    customizable: false,
  },
  {
    id: 'horchata',
    name: 'Horchata',
    category: 'drinks',
    price: 3.5,
    description: 'Sweet cinnamon rice drink, served cold.',
    image: img('soup-bowl.jpg'),
    customizable: false,
  },
];

export const GALLERY_IMAGES = [
  img('food-truck.jpg'),
  img('menu-board.jpg'),
  img('street-tacos.jpg'),
  img('plate-spread.jpg'),
  img('burrito-plate.jpg'),
  img('jarritos.jpg'),
  img('quesadilla.jpg'),
  img('taco-spread.jpg'),
  img('loaded-plate.png'),
  img('nacho-plate.jpg'),
  img('rolled-tacos.jpg'),
  img('torta-sandwich.jpg'),
];
